apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: myfliter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway #这个网关进来的
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
      proxy:
        proxyVersion: ^1\.9.* #只有这个版本才生效
      patch:
        operation: INSERT_BEFORE
        value:
          name: my.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_response(response_handle)
                response_handle:headers():add("myname", "cccc")
              end
